import type { ContentRule } from '../../../shared/types'

export const PREDEFINED_RULES: ContentRule[] = [
  {
    id: 'youtube-shorts',
    domain: 'youtube.com',
    displayName: 'YouTube Shorts',
    category: 'short_form_video',
    severity: 'high',
    selectors: [
      'ytd-shorts',
      '#shorts-container',
      '[is-shorts]',
      'ytd-reel-shelf-renderer',
      'ytd-rich-section-renderer:has([href*="/shorts/"])',
      '[title="Shorts"]',
    ],
    urlPatterns: [
      '*://*.youtube.com/shorts/*',
      '*://*.youtube.com/hashtag/shorts*',
    ],
    action: 'hide',
    antiBypassSearchTerms: ['youtube shorts', 'yt shorts', 'youtube short', 'shorts video'],
    antiBypassUrlPatterns: ['*/shorts/*', '*/?variant=shorts', 'm.youtube.com/shorts/*'],
    enabled: false, createdAt: 0, updatedAt: 0, autoApplied: false,
  },
  {
    id: 'youtube-home',
    domain: 'youtube.com',
    displayName: 'YouTube Home Feed',
    category: 'short_form_video',
    severity: 'medium',
    selectors: ['ytd-browse[page-subtype="home"] #contents'],
    urlPatterns: [],
    action: 'hide',
    antiBypassSearchTerms: [],
    antiBypassUrlPatterns: [],
    enabled: false, createdAt: 0, updatedAt: 0, autoApplied: false,
  },
  {
    id: 'youtube-sidebar',
    domain: 'youtube.com',
    displayName: 'YouTube Recommended Sidebar',
    category: 'short_form_video',
    severity: 'medium',
    selectors: ['#related', 'ytd-watch-next-secondary-results-renderer'],
    urlPatterns: [],
    action: 'hide',
    antiBypassSearchTerms: [],
    antiBypassUrlPatterns: [],
    enabled: false, createdAt: 0, updatedAt: 0, autoApplied: false,
  },
  {
    id: 'instagram-reels',
    domain: 'instagram.com',
    displayName: 'Instagram Reels',
    category: 'short_form_video',
    severity: 'high',
    selectors: [
      '[href="/reels/"]',
      'a[href*="/reel/"]',
      'article:has(video[src*="reel"])',
      'div[role="tablist"] a[href="/reels/"]',
    ],
    urlPatterns: [
      '*://*.instagram.com/reels/*',
      '*://*.instagram.com/reel/*',
    ],
    action: 'hide',
    antiBypassSearchTerms: ['instagram reels', 'ig reels', 'insta reel'],
    antiBypassUrlPatterns: ['*/reels/*', '*/reel/*'],
    enabled: false, createdAt: 0, updatedAt: 0, autoApplied: false,
  },
  {
    id: 'instagram-explore',
    domain: 'instagram.com',
    displayName: 'Instagram Explore',
    category: 'short_form_video',
    severity: 'medium',
    selectors: ['[href="/explore/"]', 'a[aria-label="Explore"]'],
    urlPatterns: ['*://*.instagram.com/explore/*'],
    action: 'hide',
    antiBypassSearchTerms: ['instagram explore'],
    antiBypassUrlPatterns: ['*/explore/*'],
    enabled: false, createdAt: 0, updatedAt: 0, autoApplied: false,
  },
  {
    id: 'tiktok-fyp',
    domain: 'tiktok.com',
    displayName: 'TikTok For You Page',
    category: 'short_form_video',
    severity: 'high',
    selectors: [
      '[data-e2e="recommend-list"]',
      '.tiktok-1g04lal-DivFeedContainer',
      '[data-e2e="feed-active-video"]',
    ],
    urlPatterns: [
      '*://*.tiktok.com/foryou*',
      '*://*.tiktok.com/',
    ],
    action: 'hide',
    antiBypassSearchTerms: ['tiktok fyp', 'tiktok for you'],
    antiBypassUrlPatterns: [],
    enabled: false, createdAt: 0, updatedAt: 0, autoApplied: false,
  },
  {
    id: 'twitter-foryou',
    domain: 'x.com',
    displayName: 'X/Twitter "For You" Feed',
    category: 'social_media',
    severity: 'medium',
    selectors: [
      '[aria-label="Timeline: Trending now"]',
      'div[aria-label="Home timeline"] a[href="/explore"]',
    ],
    urlPatterns: ['*://x.com/explore*', '*://twitter.com/explore*'],
    action: 'hide',
    antiBypassSearchTerms: ['twitter trending', 'x trending', 'twitter explore'],
    antiBypassUrlPatterns: [],
    enabled: false, createdAt: 0, updatedAt: 0, autoApplied: false,
  },
  {
    id: 'reddit-all',
    domain: 'reddit.com',
    displayName: 'Reddit r/all & r/popular',
    category: 'forums_aggregators',
    severity: 'medium',
    selectors: [
      'a[href="/r/all/"]',
      'a[href="/r/popular/"]',
      '#header-subreddit-link[href="/r/all/"]',
    ],
    urlPatterns: [
      '*://*.reddit.com/r/all/*',
      '*://*.reddit.com/r/popular/*',
    ],
    action: 'hide',
    antiBypassSearchTerms: ['reddit front page', 'r/all', 'reddit popular'],
    antiBypassUrlPatterns: ['*/r/all/*', '*/r/popular/*'],
    enabled: false, createdAt: 0, updatedAt: 0, autoApplied: false,
  },
  {
    id: 'facebook-reels',
    domain: 'facebook.com',
    displayName: 'Facebook Reels',
    category: 'short_form_video',
    severity: 'high',
    selectors: ['[aria-label*="Reels"]', '[href*="/reel/"]'],
    urlPatterns: ['*://*.facebook.com/reels*', '*://*.facebook.com/watch*'],
    action: 'hide',
    antiBypassSearchTerms: ['facebook reels', 'fb reels'],
    antiBypassUrlPatterns: ['*/reels*'],
    enabled: false, createdAt: 0, updatedAt: 0, autoApplied: false,
  },
  {
    id: 'linkedin-feed',
    domain: 'linkedin.com',
    displayName: 'LinkedIn Feed',
    category: 'social_media',
    severity: 'low',
    selectors: ['.scaffold-finite-scroll__content', '.feed-shared-update-v2'],
    urlPatterns: [],
    action: 'hide',
    antiBypassSearchTerms: ['linkedin feed'],
    antiBypassUrlPatterns: [],
    enabled: false, createdAt: 0, updatedAt: 0, autoApplied: false,
  },
]
